### ISSUE TITLE
Add a timeout parameter to Connect-VPN

### ISSUE THREAD

**Issue by JensGJ** [gildas/posh-anyconnect#5]
Using AnyConnect with Microsoft Authenticator. Sometimes the MFA prompt on the phone is delayed so much that the connection will not be approved. When I use the Cisco client directly, I get a popup showing connection timeout after a number of seconds. 
If I connect using `Connect-VPN`, I would like a similar behavior - e.g. that the request would timeout after a given period. Currently the script just hangs - also not responding to a Ctrl-C interrupt, meaning that the only way to exit the script is by killing the vpn-process or the powershell process hosting the script. 

I would suggest a `-timeout` (or perhaps `-timeoutseconds`) parameter with some reasonable default (30 seconds?)

By the way: I noticed that the posh-vpn on PowershellGallery is version 0.1.3 - published in 2016 (whereas the current version here seem to be 0.1.15, from 2020). Will PowershellGallery be updated with new version?
 
https://www.powershellgallery.com/packages/posh-vpn/0.1.3

**Comment by gildas** [comment]
Thanks for your suggestion.
Sorry for the delay, I haven't had much time to focus on this package lately.

I just updated the module to its 0.1.5 version as in this repo.

Looking into the timeout now.

**Comment by gildas** [comment]
@JensGJ, could you grab the [Connect-VPN.ps1](https://github.com/gildas/posh-vpn/blob/dev/Connect-VPN.ps1) that sits in the dev branch and give it a try?
I cannot test it anymore as I don't use Cisco VPN anymore on Windows.

Thanks!

**Comment by JensGJ** [comment]
Sure. I'm back from holiday later this week and will give it a try.

**Comment by JensGJ** [comment]
Hi - finally got the time to get back.

The timeout parameter works fine in the sense that the cmdlet terminates after the given timeout value.
Not sure if the displayed error is the desired behavior (I'd prefer the error message without the stack trace/line information)

Here is the current response from a Powershell 7 session when encountering timeout (manually set to 30 seconds in the request):


VERBOSE: Disconnected
OperationStopped: C:\Dev\Git\GitHub\posh-vpn\Connect-VPN.ps1:119
Line |
 119 |      Throw [System.TimeoutException] "Timeout ($Timeout seconds) while …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Timeout (30 seconds) while connecting to VPN.CBS.DK



Med venlig hilsen

Jens Gyldenkærne Jensen

IT-afdelingen

GRU37 – S.11

Telefon: 3815 2890

Mobil: 2114 3511





________________________________
Fra: Gildas Cherruel ***@***.***>
Sendt: 2. januar 2024 13:19
Til: gildas/posh-vpn ***@***.***>
Cc: Jens Gyldenkærne Jensen ***@***.***>; Mention ***@***.***>
Emne: Re: [gildas/posh-vpn] Add a timeout parameter to Connect-VPN (Issue #5)

Du får ikke ofte mails fra ***@***.*** Få mere at vide om, hvorfor dette er vigtigt<https://aka.ms/LearnAboutSenderIdentification>

@JensGJ<https://github.com/JensGJ>, could you grab the Connect-VPN.ps1<https://github.com/gildas/posh-vpn/blob/dev/Connect-VPN.ps1> that sits in the dev branch and give it a try?
I cannot test it anymore as I don't use Cisco VPN anymore on Windows.

Thanks!

**Comment by gildas** [comment]
Thanks for the test.

Ok, so the timeout works. Now I need to make the error nicer.
